#!/usr/bin/env bash
# Circle OS — build GrapheneOS hardened_malloc into the Circle prebuilt dir.
#
# Produces vendor/circle/prebuilt/hardened_malloc/{libhardened_malloc.so,
# Android.bp}; hardening.mk picks it up automatically (guarded, so the build is
# fine before this runs). Our fork carries any Circle patches; we never edit
# upstream in a scratch dir — this only builds it.
#
# Prereqs: git, make, ANDROID_NDK_HOME.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CIRCLE_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT="${CIRCLE_ROOT}/prebuilt/hardened_malloc"
WORK="${SCRIPT_DIR}/work"

REPO="${HARDENED_MALLOC_REPO:-https://github.com/bhengubv/hardened_malloc.git}"
REF="${HARDENED_MALLOC_REF:-circle}"
ARCH="${ARCH:-aarch64}"
APP_ABI="arm64-v8a"

die() { echo "ERROR: $*" >&2; exit 1; }

command -v git >/dev/null 2>&1 || die "git required"
command -v make >/dev/null 2>&1 || die "make required"
[ -n "${ANDROID_NDK_HOME:-}" ] || die "set ANDROID_NDK_HOME"

mkdir -p "${OUT}" "${WORK}"
[ -d "${WORK}/hardened_malloc" ] || \
  git clone --depth 1 --branch "${REF}" "${REPO}" "${WORK}/hardened_malloc"

echo "==> building hardened_malloc (${ARCH})"
( cd "${WORK}/hardened_malloc" && \
  make CONFIG_NATIVE=false ANDROID_NDK_HOME="${ANDROID_NDK_HOME}" \
       TARGET_ARCH="${ARCH}" VARIANT=default ) \
  || die "hardened_malloc build failed — check the NDK + the fork's Android make rules"

BUILT="$(find "${WORK}/hardened_malloc" -name 'libhardened_malloc.so' | head -1)"
[ -n "${BUILT}" ] || die "could not find the built libhardened_malloc.so"
install -m 0644 "${BUILT}" "${OUT}/libhardened_malloc.so"

cat > "${OUT}/Android.bp" <<BP
// Generated by fetch-hardened-malloc.sh — GrapheneOS hardened_malloc prebuilt.
cc_prebuilt_library_shared {
    name: "libhardened_malloc",
    arch: {
        arm64: {
            srcs: ["libhardened_malloc.so"],
        },
    },
    compile_multilib: "64",
    strip: { none: true },
    vendor_available: true,
    system_ext_specific: false,
    installable: true,
}
BP

echo "✓ installed ${OUT}/libhardened_malloc.so + Android.bp"
echo "  hardening.mk will now include it (ro.circle.hardened_malloc=1)."
