/*
 * Copyright (C) 2024 CircleOS
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package za.co.circleos.personalityeditor;

import android.app.Activity;
import android.app.AlertDialog;
import android.os.Bundle;
import android.os.RemoteException;
import android.util.Log;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.Toast;

import java.util.ArrayList;
import java.util.List;

import za.co.circleos.personality.ICirclePersonalityManager;
import za.co.circleos.personality.LearningSuggestion;

/**
 * Displays auto-switch learning suggestions generated by the system.
 * The user can accept (converts to a TriggerRule) or dismiss each suggestion.
 */
public class LearningSuggestionsActivity extends Activity {

    private static final String TAG = "PersonalityEditor";

    private ICirclePersonalityManager mService;
    private List<LearningSuggestion>  mSuggestions = new ArrayList<>();
    private ArrayAdapter<String>      mAdapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_learning_suggestions);
        setTitle(R.string.learning_title);

        mService = ServiceConnection.get();

        ListView list = findViewById(R.id.suggestion_list);
        mAdapter = new ArrayAdapter<>(this, android.R.layout.simple_list_item_1);
        list.setAdapter(mAdapter);

        list.setOnItemClickListener((parent, view, pos, id) ->
                showSuggestionMenu(mSuggestions.get(pos)));

        loadSuggestions();
    }

    private void loadSuggestions() {
        mSuggestions.clear();
        mAdapter.clear();
        if (mService == null) {
            Toast.makeText(this, "Service unavailable", Toast.LENGTH_SHORT).show();
            return;
        }
        try {
            List<LearningSuggestion> list = mService.getLearningSuggestions();
            if (list != null) {
                mSuggestions.addAll(list);
                for (LearningSuggestion s : mSuggestions) {
                    mAdapter.add(s.description + " [" + s.confidence + "%]");
                }
            }
            if (mSuggestions.isEmpty()) {
                mAdapter.add(getString(R.string.learning_no_suggestions));
            }
        } catch (RemoteException e) {
            Log.e(TAG, "getLearningSuggestions failed", e);
        }
    }

    private void showSuggestionMenu(LearningSuggestion sug) {
        new AlertDialog.Builder(this)
                .setTitle(R.string.learning_menu_title)
                .setMessage(sug.description)
                .setPositiveButton(R.string.learning_accept, (d, w) -> accept(sug))
                .setNegativeButton(R.string.learning_dismiss, (d, w) -> dismiss(sug))
                .setNeutralButton(android.R.string.cancel, null)
                .show();
    }

    private void accept(LearningSuggestion sug) {
        try {
            mService.acceptLearningSuggestion(sug.id);
            Toast.makeText(this, R.string.learning_accepted, Toast.LENGTH_SHORT).show();
            loadSuggestions();
        } catch (RemoteException e) {
            Log.e(TAG, "acceptLearningSuggestion failed", e);
        }
    }

    private void dismiss(LearningSuggestion sug) {
        try {
            mService.dismissLearningSuggestion(sug.id);
            loadSuggestions();
        } catch (RemoteException e) {
            Log.e(TAG, "dismissLearningSuggestion failed", e);
        }
    }
}
